batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- QObs(mm/d)
commit_hash: 8daea02
data_dir: /your/data/dir/
dataset: camels_us
device: cuda:1
dynamic_inputs:
- prcp(mm/day)
- srad(W/m2)
- tmax(C)
- tmin(C)
- vp(Pa)
epochs: 30
experiment_name: lstm_test_run
forcings: daymet
head: regression
hidden_size: 256
img_log_dir: /your/image/log/dir
initial_forget_bias: 3
learning_rate:
  0: 0.001
  15: 0.0005
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: NSE
metrics:
- MSE
- NSE
- KGE
model: cudalstm
num_workers: 8
number_of_basins: 531
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.3.0
predict_last_n: 1
run_dir: /your/nh/run/dir
save_weights_every: 1
seed: 377728
seq_length: 365
static_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
target_variables:
- QObs(mm/d)
test_basin_file: /path/to/test/basin/file.txt
test_end_date: 30/09/2005
test_start_date: 01/10/1980
train_basin_file: /path/to/train/basin/file.txt
train_dir:  /path/to/train/directory/
train_end_date: 30/09/1990
train_start_date: 01/10/1980
validate_every: 555
validate_n_random_basins: 1
validation_basin_file: /path/to/validation/basin/file.txt
validation_end_date: 30/09/1990
validation_start_date: 01/10/1980
